// flow-typed signature: 021f524ca74610d2b1ab24bfbd001aad
// flow-typed version: <<STUB>>/common-config_vhttps://github.com/nosebit/common-config.git/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'common-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'common-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'common-config/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'common-config/lib/index.js' {
  declare module.exports: $Exports<'common-config/lib/index'>;
}
